// <auto-generated />
namespace CERPA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedjobreferencetoPickorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedjobreferencetoPickorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201809071721258_Added job reference to Pickorders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
