// <auto-generated />
namespace CERPA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedconstantinvariableexpressiontodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedconstantinvariableexpressiontodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201808101321361_changed constant in variableexpression to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
